---
driver:
  name: vagrant
  customize:
    audio: none

provisioner:
  name: chef_zero
  require_chef_omnibus: 14.8.12
  data_bags_path: "../../data_bags"
  roles_path: "../../roles"
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
    driver:
      box: ubuntu/bionic64
    driver_config:
      privileged: true

suites:
  - name: default
    run_list:
      - role[ironark_base]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
